# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: LSK 50th
description: The 50th Anniversary Conference of the Linguistic Society of Korea
baseurl: "/lsk50th"
url: "https://lsk50th.github.io"

header:
  pages:
    - name: 홈
      slug: /
    - name: 기조강연
      slug: /call-for-paper
    - name: 프로그램
      slug: /program
    - name: 한국 현대언어학의 설계자들
      slug: /pioneers      
    - name: 오시는 길
      slug: /come 

footer:
  show_powered_by: true
  contact:
    - type: email
      name: lsk50th@gmail.com
      value: lsk50th@gmail.com

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
